In [1]:
import numpy as np

In [2]:
# Part 1: Smart Array Factory
def array_factory(mode, shape, value=None):
    """
    Create a NumPy array according to the requested mode.
    Modes: zeros, ones, full, identity.
    """
    if mode == "zeros":
        return np.zeros(shape)
    elif mode == "ones":
        return np.ones(shape)
    elif mode == "full":
        if value is None:
            raise ValueError("value is required when mode='full'")
        return np.full(shape, value)
    elif mode == "identity":
        if isinstance(shape, tuple):
            if len(shape) != 2 or shape[0] != shape[1]:
                raise ValueError("identity requires a square size.")
            size = shape[0]
        else:
            size = shape
        return np.eye(size)
    else:
        raise ValueError("Invalid mode. Use zeros, ones, full, or identity.")


# Examples
print(array_factory("zeros", (2, 3)))
print(array_factory("ones", (2, 3)))
print(array_factory("full", (2, 3), 7))
print(array_factory("identity", 3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# Part 2: Reshape and Stack
def secure_reshape_and_stack(data1, data2, new_shape):
    """
    Convert inputs to NumPy arrays, reshape data1, then vertically
    stack it with data2.
    """
    try:
        arr1 = np.asarray(data1)
        arr2 = np.asarray(data2)

        reshaped_arr1 = arr1.reshape(new_shape)

        if reshaped_arr1.ndim != 2 or arr2.ndim != 2:
            raise ValueError("Both datasets must be 2D after preparation.")

        if reshaped_arr1.shape[1] != arr2.shape[1]:
            raise ValueError(
                "Both matrices must have the same number of columns."
            )

        combined_dataset = np.vstack((reshaped_arr1, arr2))
        return combined_dataset

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")


In [4]:
# Part 3: Threshold
def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Replace every element >= threshold with replacement_value.
    """
    arr = np.asarray(arr)
    condition = arr >= threshold
    modified_arr = np.where(condition, replacement_value, arr)
    return modified_arr


# Correct test for Part 2
branch_a = [1, 2, 3, 4, 5, 6]
branch_b = [[7, 8, 9],
            [10, 11, 12]]

final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print("\nCombined report:")
print(final_report)
print("Shape:", final_report.shape)

# Test for Part 3
v = np.array([1, 2, 3])
print("\nThreshold result:")
print(apply_threshold(v, 2, -20))



Combined report:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)

Threshold result:
[  1 -20 -20]
