In [1]:
x = 10

In [2]:
import numpy as np

In [5]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [8]:
def init_w(shape, value = 0):
    return np.full(shape,value)

In [11]:
ones = init_w((3,4),1)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
angle = np.arange(0,361,90)
angle

array([  0,  90, 180, 270, 360])

In [ ]:
np.random.

array([[0.45034291, 0.42607366, 0.05487255],
       [0.19564529, 0.41816436, 0.92779819],
       [0.19015466, 0.32553899, 0.87120293]])

In [15]:
np.random.randint(0,11,(5,5))

array([[ 2,  6,  9,  0,  3],
       [ 3,  4,  1,  0,  8],
       [ 5,  7,  3,  5,  9],
       [ 1,  3,  2,  1, 10],
       [ 5,  4,  1,  9,  9]], dtype=int32)

In [16]:
a = ['omar','ahmed','adam']
np.random.choice(a,size=(3,5))

array([['ahmed', 'adam', 'ahmed', 'adam', 'omar'],
       ['omar', 'omar', 'adam', 'adam', 'adam'],
       ['adam', 'omar', 'adam', 'omar', 'ahmed']], dtype='<U5')

In [18]:
mat1 = np.ones((3,4))
print(mat1)
print("="*20)
mat2 = np.zeros((5,3))
print(mat2)
np.savez('np_file.npz', cat = mat1, dog = mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
with np.load('np_file.npz') as file:
    mat1 = file['cat']
    mat2 = file['dog']

print(mat1)
print("="*20)
print(mat2)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
m1 = np.array([[1,2,3],
               [0,0,0]])
m2 = np.array([[4,5,6],
               [1,1,1]])
new_mat = np.hstack((m1, m2))
new_mat

array([[1, 2, 3, 4, 5, 6],
       [0, 0, 0, 1, 1, 1]])

In [22]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,4,3,4,10])
v1 == v2

array([False, False,  True,  True, False])

In [26]:
v  = np.array([1,3,4,5,0])
np.any(v <1)

np.True_

In [30]:
v1 = np.array([2,2,3,4,5])
v2 = np.array([2,3,0,5,3])
np.allclose(v1,v2, atol = 3)


True

In [33]:
v = np.array([2,4,3,4,10])
c = 2
summation = v1 +c
print(summation)

[4 4 5 6 7]


In [34]:
pip install pandas   

Note: you may need to restart the kernel to use updated packages.


In [35]:
import pandas as pd

In [37]:
s = pd.Series([1,2,3,4], index = ['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [43]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]

data2 = {'id':[1,2,3,4],
        'sal':[444,555,666,444],
        'dep':['abc','def','ghi','xyz']}
df = pd.DataFrame(data2)
type(df)
df

,id,sal,dep
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [44]:
display(df)

,id,sal,dep
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [47]:
cols = ['col1','col2','col3']
df.columns = cols
df.columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [51]:
df['col1'] = df['col1'].astype("category")
df.dtypes

col1    category
col2       int64
col3         str
dtype: object

In [52]:
cols = ['col1', 'col2']
df[cols] = df[cols].astype("category")
df.dtypes

col1    category
col2    category
col3         str
dtype: object

In [53]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]

data2 = {'id':[1,2,3,4],
        'sal':[444,555,666,444],
        'dep':['abc','def','ghi','xyz']}
df = pd.DataFrame(data)



In [54]:
df

,0,1,2
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [64]:
df.head()

,0,1,2
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [65]:
df.describe()

,0,1
count,4.000000,4.000000
mean,2.500000,527.250000
std,1.290994,106.274409
min,1.000000,444.000000
25%,1.750000,444.000000
50%,2.500000,499.500000
75%,3.250000,582.750000
max,4.000000,666.000000


In [66]:
cols = ['col1','col2','col3']
df.columns = cols
df.columns

Index(['col1', 'col2', 'col3'], dtype='str')

In [78]:
cols = ['col1', 'col2']
df[cols] = df[cols].astype("int")
df.dtypes

col1    int64
col2    int64
col3      str
dtype: object

In [79]:
df.describe(include='number')

,col1,col2
count,4.000000,4.000000
mean,2.500000,527.250000
std,1.290994,106.274409
min,1.000000,444.000000
25%,1.750000,444.000000
50%,2.500000,499.500000
75%,3.250000,582.750000
max,4.000000,666.000000


In [ ]:
df.index

Index(['col1', 'col2', 'col3'], dtype='str')

In [84]:
x = df.col2.idxmax()
x

2

In [85]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      str  
dtypes: int64(2), str(1)
memory usage: 240.0 bytes


In [89]:
df['col2'].values

array([444, 555, 666, 444])

In [92]:
x = df.values
type(x)

numpy.ndarray

In [93]:
sort_df = df.sort_values(by='col1', ascending=False)
sort_df

,col1,col2,col3
3,4,444,xyz
2,3,666,ghi
1,2,555,def
0,1,444,abc


In [94]:
df['col1'].apply(lambda x : x*2)


0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [95]:
df.col1.iloc[2]

np.int64(3)

In [102]:
x  = df.iloc[:,0:2]
print(x)
y = df.iloc[:,-1]
print("="*20)
print(y)

   col1  col2
0     1   444
1     2   555
2     3   666
3     4   444
0    abc
1    def
2    ghi
3    xyz
Name: col3, dtype: str


In [103]:
df.drop(['col1','col2'], axis = 1)

,col3
0,abc
1,def
2,ghi
3,xyz


In [1]:
x = 10

In [2]:
import pandas as pd


In [ ]:
df = pd.read_csv('Titanic.csv')
df.head()


,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [6]:
df.drop(['PassengerId','Name',"Ticket"],axis= 1, inplace= True)

In [7]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,0,3,male,22.0,1,0,7.2500,NaN,S
1,1,1,female,38.0,1,0,71.2833,C85,C
2,1,3,female,26.0,0,0,7.9250,NaN,S
3,1,1,female,35.0,1,0,53.1000,C123,S
4,0,3,male,35.0,0,0,8.0500,NaN,S


In [ ]:
from config import DROP_CLO
from preprocess_da import drop_columns, get_data_summary
drop_columns(df,DROP_CLO)
get_data_summary(df)



In [ ]:
dtypes = df.dtypes
n_unique = df.nunique()
pd.DataFrame({"Dtypes ": dtypes, "N_unique ":n_unique}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
Dtypes,int64,int64,str,float64,int64,int64,float64,str,str
N_unique,2,3,2,88,7,7,248,147,3


891

In [22]:
null = df.isnull().sum()
ratio = (null/ df.shape[0])*100
pd.DataFrame({"null ": null, "ratio ":ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
null,0.0,0.0,0.0,177.00000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,19.86532,0.0,0.0,0.0,77.104377,0.224467


In [23]:
df = df.dropna(subset=['Embarked'])

In [24]:
df = df.drop("Cabin",axis= 1)

In [27]:
median = df['Age'].median()
df['Age'] = df['Age'].fillna(median)

In [28]:
null = df.isnull().sum()
ratio = (null/ df.shape[0])*100
pd.DataFrame({"null ": null, "ratio ":ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ratio,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
